questions = [

{"question":"Python is a ____ language.","options":["Low level","High level","Machine","Assembly"],"answer":1},
{"question":"Python was created by","options":["Dennis Ritchie","Guido van Rossum","James Gosling","Bjarne Stroustrup"],"answer":1},
{"question":"Python file extension is","options":[".pt",".py",".python",".pyt"],"answer":1},
{"question":"Which keyword defines a function?","options":["function","define","def","fun"],"answer":2},
{"question":"Which symbol is used for comments?","options":["//","#","--","/*"],"answer":1},
{"question":"Which function prints output?","options":["print()","input()","display()","show()"],"answer":0},
{"question":"Which function takes input?","options":["scan()","read()","input()","get()"],"answer":2},
{"question":"Which data type is mutable?","options":["String","Tuple","List","Integer"],"answer":2},
{"question":"Which data type is immutable?","options":["List","Dictionary","Tuple","Set"],"answer":2},
{"question":"Output of 5+2*3","options":["21","11","16","13"],"answer":1},

{"question":"Output of 10//3","options":["3","3.33","4","2"],"answer":0},
{"question":"Output of 2**4","options":["8","16","6","32"],"answer":1},
{"question":"Which operator is exponent?","options":["^","**","//","%"],"answer":1},
{"question":"Which bracket is used for lists?","options":["()","{}","[]","<>"],"answer":2},
{"question":"Which bracket is used for tuples?","options":["()","{}","[]","<>"],"answer":0},
{"question":"Which bracket is used for dictionary?","options":["()","{}","[]","<>"],"answer":1},
{"question":"Which keyword starts loop?","options":["repeat","loop","for","iterate"],"answer":2},
{"question":"Which keyword is used for conditions?","options":["when","if","check","select"],"answer":1},
{"question":"Which keyword handles multiple conditions?","options":["elseif","elif","case","otherwise"],"answer":1},
{"question":"Which loop runs until condition false?","options":["for","while","repeat","loop"],"answer":1},

{"question":"Which statement stops loop?","options":["stop","exit","break","terminate"],"answer":2},
{"question":"Which statement skips iteration?","options":["skip","continue","pass","ignore"],"answer":1},
{"question":"Which keyword defines class?","options":["object","class","define","struct"],"answer":1},
{"question":"Which function finds length?","options":["size()","count()","len()","measure()"],"answer":2},
{"question":"Which function converts to integer?","options":["float()","str()","int()","bool()"],"answer":2},
{"question":"Which function converts to string?","options":["int()","float()","str()","bool()"],"answer":2},
{"question":"Which keyword imports module?","options":["include","import","require","add"],"answer":1},
{"question":"Which module generates random numbers?","options":["math","random","time","sys"],"answer":1},
{"question":"Which module handles math operations?","options":["math","random","sys","os"],"answer":0},
{"question":"Which operator checks equality?","options":["=","==","===","!="],"answer":1},

{"question":"Which operator checks inequality?","options":["!=","<>","not=","~="],"answer":0},
{"question":"Logical AND operator","options":["&&","and","&","AND"],"answer":1},
{"question":"Logical OR operator","options":["||","or","|","OR"],"answer":1},
{"question":"Which keyword defines anonymous function?","options":["def","lambda","func","anonymous"],"answer":1},
{"question":"Which function sorts list?","options":["sort()","arrange()","order()","set()"],"answer":0},
{"question":"Which function adds element to list?","options":["add()","append()","insert()","push()"],"answer":1},
{"question":"Which function removes element from list?","options":["delete()","remove()","clear()","erase()"],"answer":1},
{"question":"Which keyword handles exception?","options":["error","try","catch","handle"],"answer":1},
{"question":"Which keyword runs when exception occurs?","options":["catch","except","error","handle"],"answer":1},
{"question":"Which keyword always runs block?","options":["final","finally","last","always"],"answer":1},

{"question":"Which function opens file?","options":["open()","read()","file()","load()"],"answer":0},
{"question":"Which mode reads file?","options":["r","w","a","x"],"answer":0},
{"question":"Which mode writes file?","options":["r","w","a","x"],"answer":1},
{"question":"Which mode appends file?","options":["r","w","a","x"],"answer":2},
{"question":"Which function closes file?","options":["end()","stop()","close()","finish()"],"answer":2},
{"question":"Boolean true keyword","options":["true","True","TRUE","1"],"answer":1},
{"question":"Boolean false keyword","options":["false","False","FALSE","0"],"answer":1},
{"question":"Identity operator","options":["==","is","===","equals"],"answer":1},
{"question":"Membership operator","options":["in","inside","within","has"],"answer":0},
{"question":"Which data structure stores key-value?","options":["list","tuple","dictionary","set"],"answer":2},

{"question":"Which keyword deletes variable?","options":["remove","delete","del","erase"],"answer":2},
{"question":"Which method converts list to string?","options":["str()","join()","append()","sort()"],"answer":0},
{"question":"Which function returns maximum value?","options":["max()","top()","largest()","biggest()"],"answer":0},
{"question":"Which function returns minimum value?","options":["min()","lowest()","bottom()","least()"],"answer":0},
{"question":"Which keyword exits program?","options":["stop","exit()","quit","break"],"answer":1},
{"question":"Which keyword defines inheritance?","options":["inherit","extends","class","parent"],"answer":2},
{"question":"Which keyword creates object?","options":["new","create","constructor","class"],"answer":3},
{"question":"Which function returns type?","options":["type()","class()","object()","kind()"],"answer":0},
{"question":"Which symbol used for floor division?","options":["/","//","%","**"],"answer":1},
{"question":"Which operator finds remainder?","options":["/","//","%","**"],"answer":2},

{"question":"Which function reverses list?","options":["reverse()","flip()","back()","turn()"],"answer":0},
{"question":"Which structure stores unique values?","options":["list","tuple","set","dictionary"],"answer":2},
{"question":"Which function merges lists?","options":["extend()","append()","add()","push()"],"answer":0},
{"question":"Which keyword defines generator?","options":["yield","return","gen","produce"],"answer":0},
{"question":"Which function reads entire file?","options":["read()","readline()","readall()","get()"],"answer":0},
{"question":"Which function reads one line?","options":["read()","readline()","line()","scan()"],"answer":1},
{"question":"Which method clears list?","options":["delete()","remove()","clear()","erase()"],"answer":2},
{"question":"Which function checks length of string?","options":["len()","size()","count()","measure()"],"answer":0},
{"question":"Which function converts to float?","options":["float()","int()","str()","bool()"],"answer":0},
{"question":"Which keyword handles multiple exceptions?","options":["except","finally","try","catch"],"answer":0},

{"question":"Which library handles dates?","options":["math","datetime","sys","os"],"answer":1},
{"question":"Which library interacts with OS?","options":["os","math","random","time"],"answer":0},
{"question":"Which library handles system functions?","options":["sys","math","random","os"],"answer":0},
{"question":"Which function returns random number?","options":["random()","rand()","generate()","randomize()"],"answer":0},
{"question":"Which function pauses program?","options":["wait()","sleep()","pause()","delay()"],"answer":1},
{"question":"Which function counts items?","options":["count()","len()","sum()","add()"],"answer":0},
{"question":"Which function sums numbers?","options":["sum()","add()","plus()","total()"],"answer":0},
{"question":"Which keyword creates loop over sequence?","options":["for","while","loop","repeat"],"answer":0},
{"question":"Which keyword handles errors?","options":["try","handle","fix","repair"],"answer":0},
{"question":"Which keyword finalizes exception block?","options":["finally","end","last","finish"],"answer":0},

{"question":"Which keyword defines a module?","options":["module","package","import","library"],"answer":2},
{"question":"Which function converts list to tuple?","options":["tuple()","list()","set()","dict()"],"answer":0},
{"question":"Which method removes last item from list?","options":["pop()","remove()","delete()","clear()"],"answer":0},
{"question":"Which function returns absolute value?","options":["abs()","absolute()","mod()","positive()"],"answer":0},
{"question":"Which keyword is used to handle errors?","options":["try","catch","fix","error"],"answer":0},
{"question":"Which function converts tuple to list?","options":["tuple()","list()","set()","dict()"],"answer":1},
{"question":"Which operator checks membership in list?","options":["has","in","inside","with"],"answer":1},
{"question":"Which keyword stops program execution?","options":["break","exit()","stop","end"],"answer":1},
{"question":"Which function rounds a number?","options":["round()","ceil()","floor()","fix()"],"answer":0},
{"question":"Which module provides system parameters?","options":["os","sys","math","random"],"answer":1},

{"question":"Which function converts string to list?","options":["list()","str()","tuple()","set()"],"answer":0},
{"question":"Which operator performs floor division?","options":["/","//","%","**"],"answer":1},
{"question":"Which function converts integer to float?","options":["float()","int()","str()","bool()"],"answer":0},
{"question":"Which method inserts element in list?","options":["append()","insert()","add()","push()"],"answer":1},
{"question":"Which keyword creates generator function?","options":["yield","return","generate","produce"],"answer":0},
{"question":"Which module generates pseudo random numbers?","options":["math","random","sys","os"],"answer":1},
{"question":"Which function converts set to list?","options":["set()","list()","tuple()","dict()"],"answer":1},
{"question":"Which keyword defines block of code?","options":["begin","def","class","block"],"answer":1},
{"question":"Which operator is modulus?","options":["/","%","//","**"],"answer":1},
{"question":"Which function checks object type?","options":["kind()","type()","class()","object()"],"answer":1}

]